{% set version = '1.0.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smoothr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/smoothr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/smoothr/smoothr_{{ version }}.tar.gz
  sha256: 580b150009934475173a6fc917020bc423934103021a8d3e6b6620d2b93fc5e9

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-sf
    - r-terra >=1.6_3
    - r-units
  run:
    - r-base
    - r-sf
    - r-terra >=1.6_3
    - r-units

test:
  requires:
    - r-testthat
    - r-sp
  files:
    - testthat.R
    - testthat/
  commands:
    - $R -e "library('smoothr')"           # [not win]
    - $R -f testthat.R                     # [not win]
    - "\"%R%\" -e \"library('smoothr')\""  # [win]


about:
  home: https://strimas.com/smoothr/, https://github.com/mstrimas/smoothr
  license: GPL-3.0-only
  summary: Tools for smoothing and tidying spatial features (i.e. lines and polygons) to make
    them more aesthetically pleasing. Smooth curves, fill holes, and remove small fragments
    from lines and polygons.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  recipe-maintainers:
    - conda-forge/r
    - Rassine

# Type: Package
# Package: smoothr
# Title: Smooth and Tidy Spatial Features
# Version: 1.0.1
# Authors@R: person(given = "Matthew", family = "Strimas-Mackey", role = c("aut", "cre"), email = "mstrimas@gmail.com", comment = c(ORCID = "0000-0001-8929-7776"))
# Description: Tools for smoothing and tidying spatial features (i.e. lines and polygons) to make them more aesthetically pleasing. Smooth curves, fill holes, and remove small fragments from lines and polygons.
# License: GPL-3
# URL: https://strimas.com/smoothr/, https://github.com/mstrimas/smoothr
# BugReports: https://github.com/mstrimas/smoothr/issues
# Depends: R (>= 3.1.2)
# Imports: sf, stats, terra (>= 1.6-3), units
# Suggests: covr, knitr, lwgeom, methods, rmarkdown, sp, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.1
# NeedsCompilation: no
# Packaged: 2023-03-09 02:39:53 UTC; mes335
# Author: Matthew Strimas-Mackey [aut, cre] (<https://orcid.org/0000-0001-8929-7776>)
# Maintainer: Matthew Strimas-Mackey <mstrimas@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-03-09 09:40:02 UTC
